# Generated by Django 3.2.5 on 2021-09-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=100)),
                ('duedays', models.IntegerField(default=0)),
                ('status', models.CharField(default='Null', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(default='Null', max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
