# Generated by Django 4.0 on 2022-02-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamleader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='workstatus',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='duedays',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='employeename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='work',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tl',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tl',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tl',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tl',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
