# Generated by Django 4.0 on 2022-02-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_emp_contact_alter_emp_email_alter_emp_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
