# Generated by Django 4.0 on 2022-02-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_emp_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='empid',
            field=models.IntegerField(null=True),
        ),
    ]
