# Generated by Django 4.0 on 2022-02-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_emp_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='empid',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
