# Generated by Django 4.0 on 2022-02-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_emp_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='project',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='tl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
