# Generated by Django 3.2.5 on 2021-09-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accesstl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(default='Null', max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=100)),
                ('platform', models.CharField(default='Null', max_length=100)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(default='Null', max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tlname', models.CharField(default='Null', max_length=100)),
                ('pmname', models.CharField(default='Null', max_length=100)),
                ('resourcename', models.CharField(max_length=100)),
                ('need', models.CharField(max_length=100)),
                ('projectname', models.CharField(default='Null', max_length=100)),
                ('onoroff', models.CharField(max_length=100)),
                ('duedays', models.CharField(max_length=100)),
                ('status', models.CharField(default='Null', max_length=50)),
                ('priority', models.CharField(default=' ', max_length=100)),
            ],
        ),
    ]
