# Generated by Django 3.2.5 on 2021-09-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='allocatestatus',
            field=models.CharField(default='', max_length=100),
        ),
    ]
