# Generated by Django 3.2.5 on 2021-09-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_resources_allocatestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='allocatestatus',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
