# Generated by Django 4.0 on 2022-02-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_alter_resources_allocatestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstl',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accesstl',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accesstl',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accesstl',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='accesstl',
            name='platform',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='duedays',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='need',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='onoroff',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='pmname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='projectname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='resourcename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='tlname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
