# Generated by Django 4.0 on 2022-02-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0005_alter_accesstl_contact_alter_manager_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
